apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-two-deployment
  namespace: tel-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-two
  template:
    metadata:
      labels:
        app: ms-two
    spec:
      containers:
        - name: ms-two
          image: sarthak8564/ms-two-k8s:test2
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: ms-two-service
  namespace: tel-ns
spec:
  selector:
    app: ms-two
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

