# Stage 1: Build the application with Maven and JDK 17
FROM maven:3.9.4-eclipse-temurin-17 AS build

WORKDIR /app

# Copy pom.xml first for dependency caching
COPY pom.xml .

# Copy all source code
COPY src ./src

# Build the jar, skip tests for faster builds (optional)
RUN mvn clean package -DskipTests

# Stage 2: Run the application with JRE 17 Alpine image
FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

# Copy jar from the build stage
COPY --from=build /app/target/ms-two-0.0.1-SNAPSHOT.jar app.jar

# Download OpenTelemetry java agent for instrumentation
ADD https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/latest/download/opentelemetry-javaagent.jar .

# Set javaagent environment variable
#ENV JAVA_TOOL_OPTIONS="-javaagent:./opentelemetry-javaagent.jar"
#ENTRYPOINT ["java", "-javaagent:./opentelemetry-javaagent.jar", "-Dotel.service.name=ms-two",  "-Dotel.traces.exporter=otlp", "-Dotel.exporter.otlp.traces.endpoint=signoz-otel-collector.signoz.svc.cluster.local:4317", "-jar", "app.jar"]
ENTRYPOINT ["java", "-javaagent:./opentelemetry-javaagent.jar", "-Dotel.service.name=ms-two", "-Dotel.traces.exporter=otlp", "-Dotel.exporter.otlp.protocol=http/protobuf", "-Dotel.exporter.otlp.endpoint=http://signoz-otel-collector.signoz.svc.cluster.local:4318", "-jar", "app.jar"]
# Run the Spring Boot jar
#ENTRYPOINT ["java", "-jar", "app.jar"]

