global:
  cloud: aws
  clusterName: DevSecOps-Cluster
  deploymentEnvironment: staging
otelCollectorEndpoint: signoz-otel-collector.signoz.svc.cluster.local:4317
otelInsecure: true
presets:
  otlpExporter:
    enabled: true
  loggingExporter:
    enabled: false
  resourceDetection:
    detectors:
      - eks
      - system

